### ISSUE TITLE
Missing ros2 feature pack

### ISSUE THREAD

**Issue by Night-elf-1** [taherfattahi/ros2-slam-auto-navigation#1]
Hello! I encountered a bug, after I installed the required environment, after executing the colcon build command and source the environment variables, The following error occurs when the launch file (ros2 launch ros2_slam_auto_navigation launch_sim.launch.py) is launched:

ros2 launch ros2_slam_auto_navigation launch_sim.launch.py 
[INFO] [launch]: All log files can be found below /home/hamster/.ros/log/2024-12-23-15-07-39-640989-hamster-NBxxTA-69769
[INFO] [launch]: Default logging verbosity is set to INFO
[ERROR] [launch]: Caught exception in launch (see debug for traceback): "package 'echo_bot_pkg' not found, searching: ['/home/hamster/mycode/ros2-slam-auto-navigation/install/ros2_slam_auto_navigation', '/opt/ros/humble']"

I can't find the echo_bot_pkg feature pack. How can I solve this problem?

**Comment by taherfattahi** [comment]
Hi @Night-elf-1, Thank you for your report! I’ve released a new version. Please pull the latest version of the source code, and the errors should be resolved.

**Comment by Night-elf-1** [comment]
thank you！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "taherfattahi/ros2-slam-auto-navigation"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月23日(星期一) 下午3:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [taherfattahi/ros2-slam-auto-navigation] Missing ros2 feature pack (Issue #1)





 
Hi @Night-elf-1, Thank you for your report! I’ve released a new version. Please pull the latest version of the source code, and the errors should be resolved.
